dist: bionic
matrix:
  include:
    - language: python
      python: "3.7.3"
      script: cd questling && coverage run --source='.' manage.py test && coverage report
    - language: node_js
      node_js: "11.15.0"
