dist: bionic
matrix:
  include:
    - language: python
      python: "3.7.3"
      install:
        - pip install -r requirements.txt --use-mirrors
        - pip install coveralls --use-mirrors
      script: cd questling && python manage.py test --parallel
      after_success: coveralls
    - language: node_js
      node_js: "11.15.0"
