# Generated by Django 2.2.1 on 2019-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
